### ISSUE TITLE
Align buttons in Nav Bar to the right

### ISSUE THREAD

**Issue by cer-nagas** [cer-nagas/cer-nagas.github.io#1]
Buttons (Home, Paintings, etc.) are now centered. Change them to right-aligned.

May change their margins / padding / size if seem fit.
![Screenshot from 2020-11-23 23-03-48](https://user-images.githubusercontent.com/10337031/100020535-421c3080-2de0-11eb-88da-9c555540ef6b.png)

**Comment by blackpandan** [comment]
hi, can you assign this to me

**Comment by cer-nagas** [comment]
> hi, can you assign this to me

Hi blackpandan, thank you very much for your help and initiation.

This project, however, is not really an open-source project in its usual meaning. It's a practice project for a (closed) group of new developers. Therefore I will not accept PRs from any external party.

Wish you the best. Keep it up with the positive energy!

**Comment by cer-nagas** [comment]
Fixed in commit c20e92116ed6fbd53f242d14ff58a013b8603e1c
